name: My Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Create tokens directory
        run: mkdir -p /home/runner/work/component-library/component-library/tokens\
      - name: Build custom properties
        run: npm run build-custom-properties
      - name: List generated files
        run: ls /home/runner/work/component-library/component-library/tokens/
      - name: Add new files
        run: git add .
      - name: Commit
        run: git commit -m "new tokens"
      - name: Push
        run: git push
    